package checker

import (
	crypto "crypto/sha256"
	"encoding/hex"
	fs "io/fs"
	"sort"

	"github.com/lizongying/nolang/cache"
	"github.com/lizongying/nolang/lexer"
	nolang "github.com/lizongying/nolang"
)

// Embedded signature table.
//
// stdsig_gen.go (generated by genstdsig) bakes the five signature tables +
// content key into the binary as Go source literals, so every `no build` skips
// PASS1 signature collection entirely. The embedded key is compared against a
// runtime hash of the embedded StdFS; if src/std changed without regenerating
// stdsig_gen.go, the keys differ and we fall through to full collection.
//
// There is no disk cache: when the embedded table is missing or stale we
// simply parse all std modules from the embedded StdFS on the fly.

// ---- embedded signature table variables (populated by stdsig_gen.go) ----
//
// When stdsig_gen.go is present (generated by genstdsig), its init() sets
// embeddedStdSigReady=true and fills the five tables + key.
// When stdsig_gen.go is NOT yet generated, embeddedStdSigReady stays false
// and CollectStdModuleSignatures falls back to full collection.
var (
	embeddedStdSigReady      = false
	embeddedStdSigVersion    = 0
	embeddedStdSigKey        = ""
	embeddedStdFuncSigs       = map[string][]string{}
	embeddedStdMethodSigs    = map[string][]string{}
	embeddedStdStructFields  = map[string]map[string]string{}
	embeddedStdAliases       = map[string]string{}
	embeddedStdStructMod     = map[string]string{}
	embeddedStdEnumVariants = map[string][]string{}
)

// computeStdSigKey returns a stable hash over all std module sources.
// Order is stabilised by sorting module paths; each module contributes its
// FullPath plus its content hash, so a rename or content change invalidates.
func computeStdSigKey() (string, error) {
	return computeStdSigKeyFromFS(nolang.StdFS)
}

// ComputeStdSigKeyFromFS is the exported, FS-parameterised variant used by
// the signature-table generator (genstdsig) to compute the same key from the
// on-disk src/ tree.
func ComputeStdSigKeyFromFS(fsys fs.FS) (string, error) {
	return computeStdSigKeyFromFS(fsys)
}

func computeStdSigKeyFromFS(fsys fs.FS) (string, error) {
	known := listStdModules(fsys)
	sorted := append([]StdModuleInfo(nil), known...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].FullPath < sorted[j].FullPath })

	h := crypto.New()
	for _, info := range sorted {
		embedPath := "std/" + info.FullPath + ".no"
		source, err := fs.ReadFile(fsys, embedPath)
		if err != nil {
			return "", err
		}
		h.Write([]byte(info.FullPath))
		h.Write([]byte{0})
		h.Write([]byte(cache.ContentKey(string(source))))
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// warmStdTokenCache ensures the global lexer token cache is populated for the
// std modules that codegen will auto-load, so they are not re-lexed from
// source. This lex-only warmup is cheap (no parsing) and runs once per process.
func warmStdTokenCache() {
	for _, info := range knownStdModules() {
		embedPath := "std/" + info.FullPath + ".no"
		source, err := nolang.StdFS.ReadFile(embedPath)
		if err != nil {
			continue
		}
		lexer.NewCached(embedPath, string(source))
	}
}
