package checker

import (
	"bytes"
	"crypto/sha256"
	"encoding/gob"
	"encoding/hex"
	"fmt"
	fs "io/fs"
	"os"
	"path/filepath"
	"sort"

	"github.com/lizongying/nolang/cache"
	"github.com/lizongying/nolang/lexer"
	nolang "github.com/lizongying/nolang"
)

// Disk cache for std module signatures.
//
// CollectStdModuleSignatures parses all ~118 std modules (≈50k LOC) on every
// `no build` merely to collect the function/struct/alias signature tables that
// the parser's type inference needs. That is a fixed ~0.5–0.9 s cost that does
// not depend on the user program. We persist the four resulting maps to a
// content-addressed gob file so subsequent builds — even in a fresh process —
// skip the parse entirely.
//
// The cache key is a hash over every std module's content (read from the
// embedded StdFS). Editing any std file, or rebuilding the `no` binary from
// changed sources, changes the key, so the stale entry is simply ignored.
// stdSigCacheVersion is bumped when the collection *logic* changes.
//
// Only the four signature tables are cached. The parsed *Program trees are NOT
// cached: parser.Program carries an unexported semantic side-table
// (SemanticContext) with potential cycles, making gob serialization unsafe; and
// the normal `no build` path never reads stdProgramsCache (it is only consumed
// by `no vet --reuse-std-ast`, which safely falls back to re-parse).

const stdSigCacheVersion = 4

// stdSigCachePayload is the on-disk representation of the four signature tables
// produced by CollectStdModuleSignatures, plus the lexed token sequences of all
// std modules. The token sequences let a warm build re-use already-lexed std
// modules during codegen auto-load (which re-parses modules from source), so the
// std parse cost is not simply shifted into the Compile phase.
type stdSigCachePayload struct {
	FuncSigs    map[string][]string
	MethodSigs  map[string][]string
	Fields      map[string]map[string]string
	Aliases     map[string]string
	StructMod   map[string]string
	EnumVariants map[string][]string
	Tokens      map[string][]lexer.Token
}

// ---- embedded signature table variables (populated by stdsig_gen.go) ----
//
// When stdsig_gen.go is present (generated by genstdsig), its init() sets
// embeddedStdSigReady=true and fills the five tables + key.
// When stdsig_gen.go is NOT yet generated, embeddedStdSigReady stays false
// and CollectStdModuleSignatures transparently falls back to the disk cache
// / full collection path.
var (
	embeddedStdSigReady      = false
	embeddedStdSigVersion    = 0
	embeddedStdSigKey        = ""
	embeddedStdFuncSigs       = map[string][]string{}
	embeddedStdMethodSigs    = map[string][]string{}
	embeddedStdStructFields  = map[string]map[string]string{}
	embeddedStdAliases       = map[string]string{}
	embeddedStdStructMod     = map[string]string{}
	embeddedStdEnumVariants = map[string][]string{}
)

// computeStdSigKey returns a stable hash over all std module sources.
// Order is stabilised by sorting module paths; each module contributes its
// FullPath plus its content hash, so a rename or content change invalidates.
func computeStdSigKey() (string, error) {
	return computeStdSigKeyFromFS(nolang.StdFS)
}

// ComputeStdSigKeyFromFS is the exported, FS-parameterised variant used by
// the signature-table generator (genstdsig) to compute the same key from the
// on-disk src/ tree.
func ComputeStdSigKeyFromFS(fsys fs.FS) (string, error) {
	return computeStdSigKeyFromFS(fsys)
}

func computeStdSigKeyFromFS(fsys fs.FS) (string, error) {
	known := listStdModules(fsys)
	sorted := append([]StdModuleInfo(nil), known...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].FullPath < sorted[j].FullPath })

	h := sha256.New()
	for _, info := range sorted {
		embedPath := "std/" + info.FullPath + ".no"
		source, err := fs.ReadFile(fsys, embedPath)
		if err != nil {
			return "", err
		}
		h.Write([]byte(info.FullPath))
		h.Write([]byte{0})
		h.Write([]byte(cache.ContentKey(string(source))))
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// stdSigCachePath returns the absolute path of the cache file for the given key.
func stdSigCachePath(key string) (string, error) {
	dir, err := os.UserCacheDir()
	if err != nil {
		dir = os.TempDir()
	}
	base := filepath.Join(dir, "nolang")
	if err := os.MkdirAll(base, 0o755); err != nil {
		return "", err
	}
	return filepath.Join(base, fmt.Sprintf("stdsig-v%d-%s.gob", stdSigCacheVersion, key)), nil
}

// tryLoadStdSigCache computes the key, opens the cache file, and decodes it.
// On a hit it also re-warms the global token cache with the persisted std token
// sequences, so the codegen auto-load path reuses already-lexed modules instead
// of re-lexing them from source. Returns (nil, false) on any error so the caller
// transparently falls back to full collection.
func tryLoadStdSigCache() (*stdSigCachePayload, bool) {
	key, err := computeStdSigKey()
	if err != nil {
		return nil, false
	}
	path, err := stdSigCachePath(key)
	if err != nil {
		return nil, false
	}
	c, ok := loadStdSigCache(path)
	if !ok {
		return nil, false
	}
	for ck, toks := range c.Tokens {
		lexer.PutCachedTokens(ck, toks)
	}
	return c, true
}

// gatherStdTokens collects the lexed token sequences of all std modules from the
// global token cache (populated by the cold CollectStdModuleSignatures parse).
// Only entries that are actually cached are returned, so a partial/missing entry
// simply falls back to re-lexing on the warm side.
func gatherStdTokens() map[string][]lexer.Token {
	tokens := make(map[string][]lexer.Token)
	for _, info := range knownStdModules() {
		embedPath := "std/" + info.FullPath + ".no"
		source, err := nolang.StdFS.ReadFile(embedPath)
		if err != nil {
			continue
		}
		ck := cache.ContentKey(string(source))
		if toks, ok := lexer.GetCachedTokens(ck); ok {
			tokens[ck] = toks
		}
	}
	return tokens
}

// warmStdTokenCache ensures the global lexer token cache is populated for the
// std modules that codegen will auto-load, so they are not re-lexed from
// source. When the disk signature cache is present we reuse its persisted
// token sequences (zero lex, matching the warm Stage-1 path); otherwise we lex
// all std modules from the embedded StdFS (cheap lex-only, no parse) as a
// one-time warmup.
func warmStdTokenCache() {
	if os.Getenv("NOLANG_NOCACHE_STD") == "" {
		if _, ok := tryLoadStdSigCache(); ok {
			return
		}
	}
	for _, info := range knownStdModules() {
		embedPath := "std/" + info.FullPath + ".no"
		source, err := nolang.StdFS.ReadFile(embedPath)
		if err != nil {
			continue
		}
		lexer.NewCached(embedPath, string(source))
	}
}

// loadStdSigCache reads and decodes the cache file.
func loadStdSigCache(path string) (*stdSigCachePayload, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, false
	}
	return decodeStdSigCache(data)
}

// decodeStdSigCache decodes a gob-encoded payload.
//
// gob decodes a non-nil empty slice as a nil slice, which breaks
// reflect.DeepEqual (nil != []T{}).  We normalise nil slices back to
// non-nil empty slices so the round-trip is byte-for-byte faithful.
func decodeStdSigCache(data []byte) (*stdSigCachePayload, bool) {
	dec := gob.NewDecoder(bytes.NewReader(data))
	var p stdSigCachePayload
	if err := dec.Decode(&p); err != nil {
		return nil, false
	}
	for k, v := range p.FuncSigs {
		if v == nil {
			p.FuncSigs[k] = []string{}
		}
	}
	for k, v := range p.MethodSigs {
		if v == nil {
			p.MethodSigs[k] = []string{}
		}
	}
	for k, v := range p.EnumVariants {
		if v == nil {
			p.EnumVariants[k] = []string{}
		}
	}
	for k, v := range p.Tokens {
		if v == nil {
			p.Tokens[k] = []lexer.Token{}
		}
	}
	return &p, true
}

// encodeStdSigCache gob-encodes a payload.
func encodeStdSigCache(p *stdSigCachePayload) ([]byte, error) {
	var buf bytes.Buffer
	enc := gob.NewEncoder(&buf)
	if err := enc.Encode(p); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// saveStdSigCache writes the payload to the cache file atomically (best-effort).
func saveStdSigCache(funcSigs map[string][]string, methodSigs map[string][]string, structFields map[string]map[string]string, aliases map[string]string, structMod map[string]string, enumVariants map[string][]string, tokens map[string][]lexer.Token) {
	key, err := computeStdSigKey()
	if err != nil {
		return
	}
	path, err := stdSigCachePath(key)
	if err != nil {
		return
	}
	data, err := encodeStdSigCache(&stdSigCachePayload{
		FuncSigs:    funcSigs,
		MethodSigs:  methodSigs,
		Fields:      structFields,
		Aliases:     aliases,
		StructMod:   structMod,
		EnumVariants: enumVariants,
		Tokens:      tokens,
	})
	if err != nil {
		return
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return
	}
	_ = os.Rename(tmp, path)
}
