// Command genstdsig generates src/checker/stdsig_gen.go, which bakes the std
// module signature tables into the `no` binary as Go source literals. This
// lets `no build` skip the PASS1 signature collection on every build,
// including the cold (first) build, without a separate //go:embed blob.
//
// It reads the on-disk src/std tree (the same files //go:embed compiles into
// StdFS), reuses the exact collection logic from the checker package, and
// emits the four maps plus the std-content key used at runtime to detect a
// stale table.
//
// Run via `go generate ./checker/` (cwd = src/checker) or `make gen`.
package main

import (
	"bytes"
	"fmt"
	goformat "go/format"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"

	"github.com/lizongying/nolang/checker"
)

const header = "// Code generated by genstdsig. DO NOT EDIT.\n" +
	"// Bakes the std module signature tables into the no binary as Go source\n" +
	"// literals so no build skips PASS1 signature collection on every build\n" +
	"// (including cold). Regenerate via 'go generate ./checker/' (or 'make gen')\n" +
	"// after editing src/std.\n\n" +
	"package checker\n\n"

func main() {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		fatal("genstdsig: cannot determine own source path")
	}
	genDir := filepath.Dir(thisFile) // .../src/checker/genstdsig
	repoRoot := filepath.Clean(filepath.Join(genDir, "..", "..", ".."))
	srcDir := filepath.Join(repoRoot, "src")
	fsys := os.DirFS(srcDir)

	funcSigs, methodSigs, structFields, aliases, structMod, err := checker.CollectStdSigsFromFS(fsys)
	if err != nil {
		fatal(fmt.Sprintf("genstdsig: collect failed: %v", err))
	}
	key, err := checker.ComputeStdSigKeyFromFS(fsys)
	if err != nil {
		fatal(fmt.Sprintf("genstdsig: key failed: %v", err))
	}

	var buf bytes.Buffer
	buf.WriteString(header)
	buf.WriteString("func init() {\n")
	buf.WriteString("\tembeddedStdSigReady = true\n")
	buf.WriteString("\tembeddedStdSigVersion = 1\n")
	fmt.Fprintf(&buf, "\tembeddedStdSigKey = %s\n", strconv.Quote(key))
	buf.WriteString("\tembeddedStdFuncSigs = ")
	writeMapStringSliceInline(&buf, funcSigs)
	buf.WriteString("\tembeddedStdMethodSigs = ")
	writeMapStringSliceInline(&buf, methodSigs)
	buf.WriteString("\tembeddedStdStructFields = ")
	writeMapStringMapInline(&buf, structFields)
	buf.WriteString("\tembeddedStdAliases = ")
	writeMapStringInline(&buf, aliases)
	buf.WriteString("\tembeddedStdStructMod = ")
	writeMapStringInline(&buf, structMod)
	buf.WriteString("}\n")

	formatted, err := goformat.Source(buf.Bytes())
	if err != nil {
		fatal(fmt.Sprintf("genstdsig: gofmt failed: %v\n---\n%s", err, buf.String()))
	}

	outPath := filepath.Join(genDir, "..", "stdsig_gen.go")
	// Preserve mtime when unchanged so incremental `make no` does not rebuild
	// the binary on every run.
	if existing, rerr := os.ReadFile(outPath); rerr == nil && bytes.Equal(existing, formatted) {
		return
	}
	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fatal(fmt.Sprintf("genstdsig: write %s: %v", outPath, err))
	}
	fmt.Printf("genstdsig: wrote %s (%d funcSigs, %d methodSigs, %d structs, %d aliases)\n",
		outPath, len(funcSigs), len(methodSigs), len(structFields), len(aliases))
}

func writeMapStringSliceInline(buf *bytes.Buffer, m map[string][]string) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if len(keys) == 0 {
		buf.WriteString("map[string][]string{}\n")
		return
	}
	buf.WriteString("map[string][]string{\n")
	for _, k := range keys {
		vals := m[k]
		fmt.Fprintf(buf, "\t%s: {", strconv.Quote(k))
		for i, v := range vals {
			if i > 0 {
				buf.WriteString(", ")
			}
			buf.WriteString(strconv.Quote(v))
		}
		buf.WriteString("},\n")
	}
	buf.WriteString("}\n")
}

func writeMapStringMapInline(buf *bytes.Buffer, m map[string]map[string]string) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if len(keys) == 0 {
		buf.WriteString("map[string]map[string]string{}\n")
		return
	}
	buf.WriteString("map[string]map[string]string{\n")
	for _, outer := range keys {
		inner := m[outer]
		ikeys := make([]string, 0, len(inner))
		for ik := range inner {
			ikeys = append(ikeys, ik)
		}
		sort.Strings(ikeys)

		fmt.Fprintf(buf, "\t%s: {\n", strconv.Quote(outer))
		for _, ik := range ikeys {
			fmt.Fprintf(buf, "\t\t%s: %s,\n", strconv.Quote(ik), strconv.Quote(inner[ik]))
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
}

func writeMapStringInline(buf *bytes.Buffer, m map[string]string) {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	if len(keys) == 0 {
		buf.WriteString("map[string]string{}\n")
		return
	}
	buf.WriteString("map[string]string{\n")
	for _, k := range keys {
		fmt.Fprintf(buf, "\t%s: %s,\n", strconv.Quote(k), strconv.Quote(m[k]))
	}
	buf.WriteString("}\n")
}

func fatal(msg string) {
	fmt.Fprintln(os.Stderr, msg)
	os.Exit(1)
}
